DROP TABLE IF EXISTS friends;
DROP TABLE IF EXISTS userData;
DROP TABLE IF EXISTS mangaData;
DROP TABLE IF EXISTS userCategories;
DROP TABLE IF EXISTS stats;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS coverImages;

CREATE TABLE IF NOT EXISTS friends (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    senderId TEXT NOT NULL,
    receiverId TEXT NOT NULL,
    status TEXT CHECK(status IN ('pending', 'accepted', 'declined')) DEFAULT 'pending',
    sentAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    respondedAt TIMESTAMP NULL,

    FOREIGN KEY (senderId) REFERENCES users(userID) ON DELETE CASCADE,
    FOREIGN KEY (receiverId) REFERENCES users(userID) ON DELETE CASCADE,

    UNIQUE (senderId, receiverId)
);

CREATE TABLE IF NOT EXISTS userData (
    userID TEXT NOT NULL,
    mangaId TEXT NOT NULL,
    currentIndex INTEGER NOT NULL,
    currentChap REAL NOT NULL,
    userCat TEXT NOT NULL,
    interactTime INTEGER NOT NULL,
    addedAt INTEGER NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (userID, mangaId),
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS mangaData (
    mangaId TEXT PRIMARY KEY NOT NULL,
    mangaName TEXT NOT NULL,
    urlBase TEXT NOT NULL,
    slugList TEXT NOT NULL,
    chapterTextList TEXT NOT NULL,
    latestChapterText REAL NOT NULL,
    updateTime TEXT NOT NULL,
    useAltStatCalc BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS userCategories (
    userID TEXT NOT NULL,
    label TEXT NOT NULL,
    value TEXT NOT NULL,
    color TEXT NOT NULL,
    stats BOOLEAN NOT NULL DEFAULT TRUE,
    public BOOLEAN NOT NULL DEFAULT FALSE,
    position INTEGER NOT NULL,

    PRIMARY KEY (userID, value),
    FOREIGN KEY (userID) REFERENCES users(userID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stats (
    "timestamp" DATETIME NOT NULL,
    "type" TEXT NOT NULL,
    "stat_value" INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    userID TEXT NOT NULL PRIMARY KEY,
    userName TEXT NOT NULL,
    imageURl TEXT,
    createdAt TIMESTAMP NOT NULL
);

CREATE TABLE NOT EXISTS coverImages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  mangaId TEXT NOT NULL,
  coverIndex INTEGER NOT NULL,
  savedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (mangaId) REFERENCES mangaData(mangaId),
  UNIQUE(mangaId, coverIndex)
);

CREATE TABLE IF NOT EXISTS userStats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mangaId TEXT NOT NULL,
    userID TEXT NOT NULL,
    value REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS mangaStats (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    type TEXT NOT NULL,
    timestamp DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mangaId TEXT,
    value REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS recommendations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    recommenderId TEXT NOT NULL,
    mangaId TEXT NOT NULL,
    receiverId TEXT NOT NULL,
    message TEXT,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

    UNIQUE (recommenderId, receiverId, mangaId)
);